/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system;

/**
 *
 * @author Shuja hassan
 */
public class Deposit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deposit.class.getName());

    /**
     * Creates new form ATM
     */
    private String cardNo;
    public Deposit(String cardNo) {
        this.cardNo = cardNo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDeposit = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDeposit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDepositMouseClicked(evt);
            }
        });
        txtDeposit.addActionListener(this::txtDepositActionPerformed);
        getContentPane().add(txtDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 310, 30));

        btnDeposit.setText("DEPOSIT");
        btnDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeposit.setPreferredSize(new java.awt.Dimension(75, 23));
        btnDeposit.addActionListener(this::btnDepositActionPerformed);
        getContentPane().add(btnDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 120, 40));

        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 120, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER THE AMOUNT YOU WANT TO DEPOSIT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 320, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atm2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 20, 1730, 580));

        setBounds(0, 0, 1635, 655);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositActionPerformed
        // TODO add your handling code here:
                txtDeposit.setText("");
    }//GEN-LAST:event_txtDepositActionPerformed

    private void txtDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDepositMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDepositMouseClicked

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        String depositAmount = txtDeposit.getText();
        if (depositAmount.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Please Enter the amount of Deposit!");
            return;
        }

        try {
            double amount = Double.parseDouble(depositAmount);
            dbConnection db = new dbConnection();
            String query = "Insert into bank(cardNo, type, amount)"+
                    "VALUES('"+ cardNo +"', '"+ "Deposit" +"', '"+ amount +"')";
            int rowsInserted = db.statement.executeUpdate(query);
            
            if (rowsInserted > 0) {
                txtDeposit.setText("");
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Rs. " + depositAmount + " Deposited successfully!");
                
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ATM atmWindoow = new ATM(this.cardNo);
        atmWindoow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deposit("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDeposit;
    // End of variables declaration//GEN-END:variables
}
