/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system;

/**
 *
 * @author Shuja hassan
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardtxt = new javax.swing.JTextField();
        pintxt = new javax.swing.JPasswordField();
        signinBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Management System");
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Card No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 70, 30));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("PIN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 27));

        cardtxt.addActionListener(this::cardtxtActionPerformed);
        getContentPane().add(cardtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 181, 30));
        getContentPane().add(pintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 181, 30));

        signinBtn.setText("Sign in");
        signinBtn.addActionListener(this::signinBtnActionPerformed);
        getContentPane().add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, -1));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 99, -1));

        signupBtn.setText("Sign up");
        signupBtn.addActionListener(this::signupBtnActionPerformed);
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 246, 33));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to ATM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        
        SignUpForm SignUpWindow = new SignUpForm();
        
        SignUpWindow.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_signupBtnActionPerformed

    private void cardtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardtxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pintxt;
    private javax.swing.JButton signinBtn;
    private javax.swing.JButton signupBtn;
    // End of variables declaration//GEN-END:variables
}
