/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Shuja hassan
 */
public class SignUp3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp3.class.getName());

    /**
     * Creates new form SignUp3
     */
    public SignUp3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbSavingAccount = new javax.swing.JRadioButton();
        rbCurrentAccount = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkAtmCard = new javax.swing.JCheckBox();
        checkMobileBanking = new javax.swing.JCheckBox();
        checkChequeBook = new javax.swing.JCheckBox();
        checkInternetBanking = new javax.swing.JCheckBox();
        checkEmailAlerts = new javax.swing.JCheckBox();
        checkStatements = new javax.swing.JCheckBox();
        CheckConfirmation = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pinCode = new javax.swing.JLabel();
        txtPinCode = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Page 3:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Account Details:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Account Type:");

        buttonGroup1.add(rbSavingAccount);
        rbSavingAccount.setText("Saving Account");

        buttonGroup1.add(rbCurrentAccount);
        rbCurrentAccount.setText("Current Account");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Card Number:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("XXXX-XXXX-XXXX-4231");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Services Required:");

        checkAtmCard.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkAtmCard.setText("ATM Card");
        checkAtmCard.addActionListener(this::checkAtmCardActionPerformed);

        checkMobileBanking.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkMobileBanking.setText("Mobile Banking");
        checkMobileBanking.addActionListener(this::checkMobileBankingActionPerformed);

        checkChequeBook.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkChequeBook.setText("Cheque Book");
        checkChequeBook.addActionListener(this::checkChequeBookActionPerformed);

        checkInternetBanking.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkInternetBanking.setText("Internet Banking");
        checkInternetBanking.addActionListener(this::checkInternetBankingActionPerformed);

        checkEmailAlerts.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkEmailAlerts.setText("Email Alerts");
        checkEmailAlerts.addActionListener(this::checkEmailAlertsActionPerformed);

        checkStatements.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        checkStatements.setText("E-Statements");
        checkStatements.addActionListener(this::checkStatementsActionPerformed);

        CheckConfirmation.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        CheckConfirmation.setText("I hereby declare that the above details are correct and the best of my knowledge");
        CheckConfirmation.addActionListener(this::CheckConfirmationActionPerformed);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        jLabel6.setText("(It would appear on your Debit/Credit Card)");

        pinCode.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        pinCode.setText("Pin:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel9.setText("(Your 16-Digits card number)");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel10.setText("(4-Digits Code)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAtmCard, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkMobileBanking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkChequeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkInternetBanking, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(checkEmailAlerts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkStatements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCurrentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(pinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSavingAccount)
                    .addComponent(rbCurrentAccount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAtmCard)
                    .addComponent(checkInternetBanking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMobileBanking)
                    .addComponent(checkEmailAlerts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkChequeBook)
                    .addComponent(checkStatements))
                .addGap(37, 37, 37)
                .addComponent(CheckConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAtmCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAtmCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAtmCardActionPerformed

    private void checkMobileBankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMobileBankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMobileBankingActionPerformed

    private void checkChequeBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkChequeBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkChequeBookActionPerformed

    private void checkInternetBankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInternetBankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInternetBankingActionPerformed

    private void checkEmailAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmailAlertsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEmailAlertsActionPerformed

    private void checkStatementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkStatementsActionPerformed

    private void CheckConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckConfirmationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckConfirmationActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String accType = "";
        if (rbCurrentAccount.isSelected()) {
            accType = "Current";
        }
        else if (rbSavingAccount.isSelected()) {
            accType = "Saving";
        }
        
        if (accType.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select the account type");
            return;
        }
        
        Random ran = new Random();
        Long first7 = (ran.nextLong() % 90000000L) + 1409963000000000L;
        String cardNo = "" + Math.abs(first7);
        String formattedCardNo = cardNo.replaceAll(".{4}(?!$)", "$0-");
        
        String pin = txtPinCode.getText();
       
        ArrayList<String> SelectedServices = new ArrayList<>();
        
        if (checkAtmCard.isSelected()) {
            SelectedServices.add(checkAtmCard.getText());
        }
        if (checkChequeBook.isSelected()) {
            SelectedServices.add(checkChequeBook.getText());
        }
        if (checkEmailAlerts.isSelected()) {
            SelectedServices.add(checkEmailAlerts.getText());
        }
        if (checkInternetBanking.isSelected()) {
            SelectedServices.add(checkInternetBanking.getText());
        }
        if (checkMobileBanking.isSelected()) {
            SelectedServices.add(checkMobileBanking.getText());
        }
        if (checkStatements.isSelected()) {
            SelectedServices.add(checkStatements.getText());
        }
        
        String servicesString = String.join(",", SelectedServices);
        
        if (servicesString.isEmpty()) {
            javax.swing.JOptionPane.showConfirmDialog(this, "Please select a service!");
            return;
        }
        
        if (!CheckConfirmation.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(null, "You must check the confirmation box to proceed.");
        return;
        }
       
        try {
            dbConnection db = new dbConnection();
            
            String query1 = "Insert into signupThree(accountType, cardNo, pinCode, services) "+
                    "values('"+ accType +"', '"+ formattedCardNo +"' , '"+ pin +"' , '"+ servicesString +"')";
            String query2 = "Insert into Login (cardNo, pinCode)"+
                    "VALUES('"+ formattedCardNo +"', '"+ pin +"')";
            db.statement.executeUpdate(query1);
            db.statement.executeUpdate(query2);
            
            javax.swing.JOptionPane.showMessageDialog(null, "Card No: "+ formattedCardNo+ "\n Pin: "+ pin);
            setVisible(false);
            
        } catch (Exception e) {
            System.out.println("Error saving details!" + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Database error" + e.getMessage(), "Error" , JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
           
        
        
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckConfirmation;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkAtmCard;
    private javax.swing.JCheckBox checkChequeBook;
    private javax.swing.JCheckBox checkEmailAlerts;
    private javax.swing.JCheckBox checkInternetBanking;
    private javax.swing.JCheckBox checkMobileBanking;
    private javax.swing.JCheckBox checkStatements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel pinCode;
    private javax.swing.JRadioButton rbCurrentAccount;
    private javax.swing.JRadioButton rbSavingAccount;
    private javax.swing.JPasswordField txtPinCode;
    // End of variables declaration//GEN-END:variables
}
