/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system;
import java.sql.ResultSet;

/**
 *
 * @author Shuja hassan
 */
public class Withdrawl extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Withdrawl.class.getName());

    /**
     * Creates new form ATM
     */
    private String cardNo;
    public Withdrawl(String cardNo) {
        this.cardNo = cardNo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWithdraw = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWithdraw.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWithdrawMouseClicked(evt);
            }
        });
        txtWithdraw.addActionListener(this::txtWithdrawActionPerformed);
        getContentPane().add(txtWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 310, 30));

        btnWithdraw.setText("WITHDRAW");
        btnWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithdraw.addActionListener(this::btnWithdrawActionPerformed);
        getContentPane().add(btnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 120, 40));

        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 120, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLEASE ENTER YOUR AMOUNT ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 320, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atm2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 20, 1730, 580));

        setBounds(0, 0, 1635, 655);
    }// </editor-fold>//GEN-END:initComponents

    private void txtWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWithdrawActionPerformed
        // TODO add your handling code here:
                txtWithdraw.setText("");
    }//GEN-LAST:event_txtWithdrawActionPerformed

    private void txtWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWithdrawMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtWithdrawMouseClicked

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        String withdrawAmount = txtWithdraw.getText();
        if (withdrawAmount.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Please Enter the amount to Withdraw!");
            return;
        }

        try {
            double AmountToWithdraw = Double.parseDouble(withdrawAmount);
            
            double currentBalance = 0;
            
            dbConnection db = new dbConnection();
            
            String query = "Select type, amount FROM bank WHERE cardNo = '"+ cardNo +"'";            
            ResultSet resultSet = db.statement.executeQuery(query);
            
            while (resultSet.next()) {
                if (resultSet.getString("type").equalsIgnoreCase("Deposit")) {
                    currentBalance += resultSet.getDouble("amount");
                } else if (resultSet.getString("type").equalsIgnoreCase("Withdraw")) {
                    currentBalance -= resultSet.getDouble("amount");
                }
            }
            
            if (currentBalance < AmountToWithdraw) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Insufficient Balance! Your current balance is Rs. " + currentBalance);
            return;
            }
            
            String withdrawQuery = "Insert into bank (cardNo, type, amount)"+
                    "VALUES('"+ cardNo +"', '"+ "Withdraw" +"', '"+ AmountToWithdraw +"')";
             
            db.statement.executeUpdate(withdrawQuery);  
            
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Rs. " + AmountToWithdraw + " Debited Successfully!");
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ATM atmWindoow = new ATM(this.cardNo);
        atmWindoow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Withdrawl("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtWithdraw;
    // End of variables declaration//GEN-END:variables
}
